name: Lint
on: push

jobs:
  lint:
    name: Lint codes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.44.0
      - name: run golangci-lint
        run: make lint

